### ISSUE TITLE
Modifying `$GuiCompletionConfig` has no effect

### ISSUE THREAD

**Issue by thorstenkampe** [cspotcode/PS-GuiCompletion#11]
Modifying colors or other settings via `$GuiCompletionConfig`  in `$PROFILE` or interactively has no effect - while modifications in `default-config.ps1` have the desired effect.

This seems to be a bug and not a user error because `$GuiCompletionConfig.DoubleBorder = $false` (for instance) has no effect while `$PowerTabConfig.DoubleBorder = $false` (with `PowerTab` instead of `GuiCompletion` imported) works.

**Comment by thorstenkampe** [comment]
I figured it out:
- wrong way: rip data structure from `default-config.ps1` and put it in `$PROFILE`
```
$GuiCompletionConfig = @{
    Colors = @{
        BackColor = 'DarkBlue';
        [...]
    };
    DoubleBorder = $false
}
```
- Correct way
```
$GuiCompletionConfig.Colors = @{
        BackColor = 'DarkBlue';
        [...]
}
$GuiCompletionConfig.DoubleBorder = $false
```
or
```
$GuiCompletionConfig.Colors.BackColor= 'DarkBlue'
[...]
$GuiCompletionConfig.DoubleBorder = $false
```

**Comment by nightroman** [comment]
It looks like it was a user error after all :)

**GuiCompletion** 0.10.0 makes this kind of error impossible, users cannot assign this variable.
Note that development moved to https://github.com/nightroman/PS-GuiCompletion
