### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by cspotcode** [cspotcode/PS-GuiCompletion#4]
Fuzzy matching means you can omit parts of the string you want to match.  For example, type "-lip" and it'll  match "-LiteralPath".

For performance it probably makes sense to implement the filtering in a background thread.  (See #3)

This library implements a fuzzy matching algorithm; are there C# implementations I can use?  https://github.com/atom/fuzzaldrin
C# possibility:
https://github.com/kdjones/fuzzystring

Nice-to-haves: render with matched characters highlighted a-la VSCode

**Comment by majkinetor** [comment]
This would be awesome to have. In powershell you get fuzzy matching if you insert * between each letter: -`'literalpath' -like '*l*i*p*'`

**Comment by nightroman** [comment]
This is done here
https://github.com/nightroman/PS-GuiCompletion/tree/04-my-filter

Please try this (with many other improvements) and give some feedback.

I am planning to push this to the main repo but I am waiting for some feedback from @cspotcode and hopefully other users.

**Comment by nightroman** [comment]
Fuzzy filter is implemented and engaged in just released v0.9.0.
Note that new development moved to https://github.com/nightroman/PS-GuiCompletion
